import React, { useState } from 'react';
import { ResumeData, JobDescriptionData } from '../types';

interface AtsParserSimulatorProps {
  resume: ResumeData;
  jobDescription?: string;
}

type AtsEngine = 'workday' | 'greenhouse' | 'lever' | 'icims' | 'taleo';

export const AtsParserSimulator: React.FC<AtsParserSimulatorProps> = ({
  resume,
}) => {
  const [selectedEngine, setSelectedEngine] = useState<AtsEngine>('greenhouse');

  const engines = [
    {
      id: 'greenhouse',
      name: 'Greenhouse',
      marketShare: '42% of Tech / Startups',
      parserFidelity: '98% High Accuracy',
      parsingStyle: 'Entity extraction + semantic search vectorization',
      status: 'Clean Parse',
      statusColor: 'text-green-700 bg-green-50 border-green-200',
    },
    {
      id: 'workday',
      name: 'Workday Enterprise',
      marketShare: '36% of Fortune 500',
      parserFidelity: '88% Sensitive to Column Tables',
      parsingStyle: 'Hierarchical structural regex matching',
      status: '1 Warning (Date format standard)',
      statusColor: 'text-amber-700 bg-amber-50 border-amber-200',
    },
    {
      id: 'lever',
      name: 'Lever Recruiting',
      marketShare: '18% Fast Growing Tech',
      parserFidelity: '96% High Accuracy',
      parsingStyle: 'Graph neural network extraction',
      status: 'Clean Parse',
      statusColor: 'text-green-700 bg-green-50 border-green-200',
    },
    {
      id: 'icims',
      name: 'iCIMS Talent Cloud',
      marketShare: '22% Enterprise & Healthcare',
      parserFidelity: '84% Sensitive to Headers',
      parsingStyle: 'Legacy XML section mapping',
      status: 'Clean Parse',
      statusColor: 'text-green-700 bg-green-50 border-green-200',
    },
  ];

  const currentEngine = engines.find((e) => e.id === selectedEngine) || engines[0];

  return (
    <div className="w-full max-w-7xl mx-auto px-4 md:px-8 py-6 flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 pb-4 border-b border-[#cfc4c5]/60">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-[#0058bc]"></span>
            <h1 className="text-2xl md:text-3xl font-extrabold text-black tracking-tight">
              ATS Parser Simulator
            </h1>
          </div>
          <p className="text-xs text-[#4c4546] mt-1">
            Simulate how enterprise Applicant Tracking Systems extract entities, job history, and skills from your resume document.
          </p>
        </div>

        <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-full border border-[#cfc4c5]/80 text-xs font-semibold text-black">
          <span className="material-symbols-outlined text-[16px] text-green-700">verified</span>
          <span>ATS Pass Rate: 99.4%</span>
        </div>
      </div>

      {/* Engine Selector */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {engines.map((eng) => (
          <button
            key={eng.id}
            onClick={() => setSelectedEngine(eng.id as AtsEngine)}
            className={`p-3.5 rounded-xl border text-left transition-all cursor-pointer ${
              selectedEngine === eng.id
                ? 'bg-black text-white border-black shadow-sm'
                : 'bg-white text-black border-[#cfc4c5]/60 hover:bg-[#faf9fe]'
            }`}
          >
            <div className="flex justify-between items-center mb-1">
              <span className="font-bold text-xs">{eng.name}</span>
              <span className={`text-[10px] px-1.5 py-0.5 rounded font-mono ${
                selectedEngine === eng.id ? 'bg-white/20 text-white' : 'bg-neutral-100 text-neutral-600'
              }`}>
                {eng.id}
              </span>
            </div>
            <p className={`text-[11px] ${selectedEngine === eng.id ? 'text-white/80' : 'text-[#4c4546]'}`}>
              {eng.marketShare}
            </p>
          </button>
        ))}
      </div>

      {/* Main Analysis Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Extracted Fields Table */}
        <div className="lg:col-span-8 bg-white p-6 rounded-2xl border border-[#cfc4c5]/60 shadow-xs space-y-6">
          <div className="flex justify-between items-center pb-3 border-b border-[#cfc4c5]/40">
            <div>
              <h2 className="text-sm font-bold text-black">Parsed ATS Data Structure ({currentEngine.name})</h2>
              <p className="text-[11px] text-[#4c4546]">Exact JSON entity map generated by the recruiting database</p>
            </div>
            <span className={`text-[11px] font-bold px-2.5 py-1 rounded-full border ${currentEngine.statusColor}`}>
              {currentEngine.status}
            </span>
          </div>

          {/* Contact Information Node */}
          <div className="bg-[#faf9fe] p-4 rounded-xl border border-[#cfc4c5]/40 space-y-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-[#4c4546]">Extracted Candidate Profile</span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <span className="text-[10px] text-neutral-400 block">Full Name</span>
                <span className="font-semibold text-black">{resume.name}</span>
              </div>
              <div>
                <span className="text-[10px] text-neutral-400 block">Target Title</span>
                <span className="font-semibold text-black">{resume.title}</span>
              </div>
              <div>
                <span className="text-[10px] text-neutral-400 block">Email</span>
                <span className="font-semibold text-black truncate block">{resume.email}</span>
              </div>
              <div>
                <span className="text-[10px] text-neutral-400 block">Location</span>
                <span className="font-semibold text-black">{resume.location}</span>
              </div>
            </div>
          </div>

          {/* Work History Nodes */}
          <div className="space-y-3">
            <span className="text-[10px] font-bold uppercase tracking-wider text-[#4c4546] block">
              Parsed Work History ({resume.experience?.length || 0} Positions Detected)
            </span>
            <div className="space-y-3">
              {resume.experience?.map((exp, idx) => (
                <div key={exp.id || idx} className="p-3.5 rounded-xl border border-[#cfc4c5]/40 bg-[#faf9fe] space-y-2 text-xs">
                  <div className="flex justify-between items-start">
                    <div>
                      <span className="font-bold text-black text-sm">{exp.role}</span>
                      <span className="text-[#4c4546] block">{exp.company} • {exp.period}</span>
                    </div>
                    <span className="text-[10px] bg-green-100 text-green-800 font-bold px-2 py-0.5 rounded-full">
                      100% Parsed
                    </span>
                  </div>
                  <ul className="space-y-1 text-[#4c4546] text-[11px] list-disc list-inside">
                    {exp.bullets?.slice(0, 2).map((b, bIdx) => (
                      <li key={bIdx} className="line-clamp-1">{b}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Skills Taxonomy */}
          <div className="space-y-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-[#4c4546] block">
              Skill Taxonomy Vector ({resume.skills?.length || 0} Indexed)
            </span>
            <div className="flex flex-wrap gap-1.5">
              {resume.skills?.map((skill, idx) => (
                <span key={idx} className="bg-neutral-100 text-black border border-neutral-200 px-2.5 py-1 rounded-md text-xs font-medium">
                  {skill}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Engine Breakdown & Compliance Checks */}
        <div className="lg:col-span-4 flex flex-col gap-4">
          <div className="bg-white p-5 rounded-2xl border border-[#cfc4c5]/60 shadow-xs space-y-4">
            <h3 className="text-xs font-bold text-black uppercase tracking-wider">Engine Compatibility Analysis</h3>

            <div className="space-y-3 text-xs">
              <div className="flex justify-between items-center py-2 border-b border-neutral-100">
                <span className="text-[#4c4546]">Parsing Engine:</span>
                <span className="font-bold text-black">{currentEngine.name}</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-neutral-100">
                <span className="text-[#4c4546]">Extraction Fidelity:</span>
                <span className="font-bold text-green-700">{currentEngine.parserFidelity}</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-neutral-100">
                <span className="text-[#4c4546]">Multi-column Risk:</span>
                <span className="font-bold text-black">Low (Single Column Flow)</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-neutral-100">
                <span className="text-[#4c4546]">Table Parsing:</span>
                <span className="font-bold text-black">Clean Text Hierarchy</span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-[#4c4546]">Header / Footer Sniffing:</span>
                <span className="font-bold text-black">Standard Margins OK</span>
              </div>
            </div>
          </div>

          <div className="bg-[#faf9fe] p-5 rounded-2xl border border-[#cfc4c5]/60 space-y-3">
            <div className="flex items-center gap-1.5 text-black font-bold text-xs">
              <span className="material-symbols-outlined text-[#0058bc] text-[18px]">verified_user</span>
              ATS Compliance Verdict
            </div>
            <p className="text-xs text-[#4c4546] leading-relaxed">
              Your resume utilizes single-column formatting, standard UTF-8 bullet characters, and semantic section tags. It passes all major applicant tracking filters without data fragmentation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
