import type { NextFunction, Request, Response } from 'express';
import { login, publicUser, register } from '../services/authService.js';
import { sendSuccess } from '../utils/response.js';
const failValidation = (message: string) => { throw Object.assign(new Error(message), { statusCode: 400, code: 'VALIDATION_ERROR' }); };
const passwordValid = (value: string) => value.length >= 8 && /[A-Z]/.test(value) && /[a-z]/.test(value) && /\d/.test(value) && /[^A-Za-z0-9]/.test(value);
export async function handleRegister(req: Request, res: Response, next: NextFunction) { try { const { name, email, username, mobile, password, targetRole } = req.body; if (typeof name !== 'string' || name.trim().length < 2 || !/[A-Za-z]/.test(name)) failValidation('Please enter your full name.'); if (typeof email !== 'string' || !/^\S+@\S+\.\S+$/.test(email)) failValidation('Please enter a valid email address.'); if (typeof username !== 'string' || !/^[A-Za-z0-9_]{4,}$/.test(username)) failValidation('Username must contain at least 4 letters, numbers, or underscores and no spaces.'); if (typeof mobile !== 'string' || !/^\+?[0-9\s()-]{8,20}$/.test(mobile)) failValidation('Please enter a valid mobile number.'); if (typeof password !== 'string' || !passwordValid(password)) failValidation('Password must contain at least 8 characters, including uppercase, lowercase, number and special character.'); sendSuccess(res, { data: await register({ name, email, username, mobile, password, targetRole }) }, 201); } catch (e) { next(e); } }
export async function handleLogin(req: Request, res: Response, next: NextFunction) { try { const { identifier, email, password } = req.body; const loginId = identifier ?? email; if (typeof loginId !== 'string' || !loginId.trim()) failValidation('Please enter your User ID or email.'); if (typeof password !== 'string' || !password) failValidation('Please enter your password.'); sendSuccess(res, { data: await login(loginId, password) }); } catch (e) { next(e); } }
export async function handleAdminLogin(req: Request, res: Response, next: NextFunction) { try { const { email, password } = req.body; sendSuccess(res, { data: await login(email || '', password || '', true) }); } catch (e) { next(e); } }
export function handleMe(req: Request, res: Response) { sendSuccess(res, { data: { user: publicUser(req.user!) } }); }
