import type { NextFunction, Request, Response } from 'express';
import { AppError, sendSuccess } from '../utils/response.js';
import { ids } from '../utils/ids.js';
import { getDb, persist } from '../repositories/store.js';
const collection = (kind: 'resumes' | 'jobs') => async (req: Request, res: Response, next: NextFunction) => { try { const list = (await getDb())[kind].filter((item: any) => item.userId === req.user!.id); sendSuccess(res, { data: list }); } catch (e) { next(e); } };
const create = (kind: 'resumes' | 'jobs') => async (req: Request, res: Response, next: NextFunction) => { try { const now = new Date().toISOString(); const body = req.body || {}; if (typeof body.title !== 'string' || !body.title.trim()) throw new AppError('A title is required', 400, 'VALIDATION_ERROR'); if (kind === 'resumes' && (typeof body.name !== 'string' || !Array.isArray(body.skills))) throw new AppError('Resume name and skills are required', 400, 'VALIDATION_ERROR'); if (kind === 'jobs' && typeof body.description !== 'string') throw new AppError('Job description is required', 400, 'VALIDATION_ERROR'); const item = { ...body, id: kind === 'resumes' ? ids.resume() : ids.job(), userId: req.user!.id, skills: kind === 'resumes' ? [...new Set(body.skills.map((s: unknown) => String(s).trim()).filter(Boolean))] : undefined, createdAt: now, updatedAt: now }; const db = await getDb(); (db[kind] as any[]).push(item); await persist(); sendSuccess(res, { data: item }, 201); } catch (e) { next(e); } };
const update = (kind: 'resumes' | 'jobs') => async (req: Request, res: Response, next: NextFunction) => { try { const item = (await getDb())[kind].find((entry: any) => entry.id === req.params.id && entry.userId === req.user!.id); if (!item) throw new AppError('Record not found', 404, 'NOT_FOUND'); Object.assign(item, req.body, { id: item.id, userId: item.userId, createdAt: item.createdAt, updatedAt: new Date().toISOString() }); await persist(); sendSuccess(res, { data: item }); } catch (e) { next(e); } };
const remove = (kind: 'resumes' | 'jobs') => async (req: Request, res: Response, next: NextFunction) => { try { const db = await getDb(); const index = (db[kind] as any[]).findIndex(entry => entry.id === req.params.id && entry.userId === req.user!.id); if (index < 0) throw new AppError('Record not found', 404, 'NOT_FOUND'); (db[kind] as any[]).splice(index, 1); await persist(); sendSuccess(res, { message: 'Record deleted' }); } catch (e) { next(e); } };
export const listResumes = collection('resumes'); export const createResume = create('resumes'); export const updateResume = update('resumes'); export const deleteResume = remove('resumes'); export const listJobs = collection('jobs'); export const createJob = create('jobs'); export const updateJob = update('jobs'); export const deleteJob = remove('jobs');
